### ISSUE TITLE
Implementation plans?

### ISSUE THREAD

**Issue by akx** [Bluetooth-Devices/ruuvitag-ble#1]
Hi there!

Are there implementation plans for this repo yet? 

I had been using my https://github.com/akx/ruuvidriver project with a REST sensor to work with Ruuvi tags in my HA installation (IOW I'm an old hand at working with Ruuvitags), but apparently the new cool thing is to let HA do it yourself with the help of these repos.

If there are no people working on this, I'd be glad to give it a shot.

**Comment by akx** [comment]
Update – I have some initial untested code (working out of a local bar right now and there aren't any Ruuvitags around, boo) at https://github.com/akx/ruuvitag-ble/tree/initial-dev – I'll try it out and fix any inevitable problems and see where I can get to...

**Comment by chris-est** [comment]
Hey, thank you for starting to work on this.
I tried to test your code but could not get it to work. Could you give me some directions (i am a HA newbie ;-) )?

My Setup is:
* RPi4 with integrated bluetooth
* installed HA using the [command line setup](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core)
* followed the link to your repo
* cloned the repo (+switched branches)
* did the pip install with the homeassistant user
* restarted RPi + HA

In the HA webinterface i tried Settings - Devices + Services - Add Integration. I see a bluetooth device but no RuuviTags, where should i look for it?

**Comment by akx** [comment]
I didn't get it to work either yet, so don't worry :) I realized it'll also need bits in the main HA repo (or a custom component), but I'm working on that (too!).

**Comment by chris-est** [comment]
Thanks for the update!
I don't think i will be very helpful for implemetation stuff as i know nothing about HA internals, but i would be happy to help testing a first version.

**Comment by akx** [comment]
@chris-est Things are underway 😄 

Please follow https://github.com/home-assistant/core/pull/81327 for the HA bits... I'll close this issue for now.
